### ISSUE TITLE
Static functions and new classes

### ISSUE THREAD

**Issue by bmeikle56** [bmeikle56/TransACT#38]
should the static functions that handle login/signup and failures (emailIsValid), other functions (clearFields) belong to some new class -> currently they are in SignUpView or ResetPasswordView and it makes little sense to keep them there when they are used in multiple classes so we could create a new class or two to hold those functions

should Firebase login/signup be static and placed in a new class for the same reason?

**Comment by scheng82** [comment]
I set up `LocationManager` and `NotificationManager` for location and notification logic separately. Logically it is cleaner. I think it makes sense for utility functions like `emailsValid` to also be in a separate class so that multiple views can call it directly as a toolbox, as `emailsValid` is now already shared between SignUpView and ResetPasswordView. If we have other priorities, we can proceed with new functionalities and label this as a refactor. We can come back to this later
